# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2
updates:
- package-ecosystem: github-actions
  schedule:
    interval: daily
  directory: /
  labels: [ğŸ“š dependencies]
  commit-message:
    prefix: â¬†ï¸
    include: scope
- package-ecosystem: swift
  schedule:
    interval: daily
  directory: /
  labels: [ğŸ“š dependencies]
  commit-message:
    prefix: â¬†ï¸
    include: scope
