osx_image: xcode8.3
language: generic
matrix:
  include:
    - os: osx
      env:
        - PLATFORM=macos
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=macos
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      env:
        - PLATFORM=ios
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      env:
        - PLATFORM=tvos
        - XCODE_ACTION="build-for-testing test-without-building"
    - os: osx
      env:
        - PLATFORM=swiftpm
    - os: osx
      osx_image: xcode9.3
      env:
        - PLATFORM=swiftpm
    - os: osx
      env:
        - PODSPEC=1
    - os: linux
      sudo: required
      dist: trusty
    - os: linux
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION=4.1
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./script/travis-install-macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-install-linux; fi
  - if [[ "$PODSPEC" ]]; then gem install bundler; bundle install; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then ./script/travis-script-macos; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-script-linux; fi
  - if [[ "$PODSPEC" ]]; then danger; fi
